language: node_js
node_js:
 - "node"
 
env:
 global:
  - SAUCE_USERNAME=B3nCr
  - SAUCE_ACCESS_KEY=5826ebd7-beb4-452b-bb10-7feb97c89e4e
 
before_script:
 - npm install -g grunt
 - npm install -g protractor
 - npm build
script: npm test
addons:
  sauce_connect: true
