language: node_js
node_js:
 - "iojs"
before_script:
 - npm install -g grunt
 - npm install -g protractor
 - npm build
script: npm test
addons:
  sauce_connect:
    username: "B3nCr"
    access_key: "5826ebd7-beb4-452b-bb10-7feb97c89e4e"